services:
  dashboard:
    image: dashboard
    env_file:
      - .env
    ports:
      - "8050:8050"
    volumes:
      - ./:/DS6600-congress
    networks:
      - dbnetwork


  # jupyterlab:
  #   image: jupyterdocker
  #   env_file:
  #     - .env
  #   ports:
  #     - "8888:8888"
  #   volumes:
  #     - ./:/DS6600-congress
  #   networks:
  #     - dbnetwork

  postgres:
    image: postgres:17.6
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - dbnetwork

  # mysql:
  #   image: mysql
  #   env_file:
  #     - .env
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - mysqldata:/var/lib/mysql
  #   networks:
  #     - dbnetwork
  
  mongo:
    image: mongo
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - dbnetwork      

volumes:
  postgresdata:
  # mysqldata:
  mongodata:

networks:
  dbnetwork:
